name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cp .env.testing .env
    - name: Install Dependencies
      run: composer install
    - name: Install NPM Dependencies
      run: npm install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.pgsql
    - name: Execute tests (Unit and Feature tests) via PHPUnit still have to fix database 
      env:
        DB_CONNECTION: pgsql
        DB_DATABASE: database/database.pgsql
      run: |
        php artisan migrate
        vendor/bin/phpunit
